### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by Takeos** [liaozixu/githubGreen-csharp#1]
环境win8，点击start，好像提示星期错误无法继续执行

**Comment by liaozixu** [comment]
start time不能晚于end time

**Comment by Takeos** [comment]
# start time是晚于end 的，错误提示如下：




有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.FormatException: 由于星期几不正确，该字符串未被识别为有效的 DateTime。
   在 System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   在 System.Convert.ToDateTime(String value)
   在 com.liaozixu.githubGreen.from.main.button2_Click(Object sender, EventArgs e)
   在 System.Windows.Forms.Control.OnClick(EventArgs e)
   在 System.Windows.Forms.Button.OnClick(EventArgs e)
   在 System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   在 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.ButtonBase.WndProc(Message& m)
   在 System.Windows.Forms.Button.WndProc(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** 已加载的程序集 **************
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:4.0.30319.34011 built by: FX45W81RTMGDR
    基本代码:file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
githubGreen
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    基本代码:file:///C:/Users/Administrator/Downloads/githubGreen.exe
----------------------------------------
System.Windows.Forms
    程序集版本:4.0.0.0
    Win32 版本:4.0.30319.33440 built by: FX45W81RTMREL
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    程序集版本:4.0.0.0
    Win32 版本:4.0.30319.33440 built by: FX45W81RTMREL
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    程序集版本:4.0.0.0
    Win32 版本:4.0.30319.34111 built by: FX45W81RTMGDR
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
mscorlib.resources
    程序集版本:4.0.0.0
    Win32 版本:4.0.30319.33440 built by: FX45W81RTMREL
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本:4.0.0.0
    Win32 版本:4.0.30319.33440 built by: FX45W81RTMREL
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

例如:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

启用 JIT 调试后，任何未经处理的异常
都将被发送到在此计算机上注册的 JIT 调试器，
而不是由此对话框处理。

**Comment by liaozixu** [comment]
你好，因为手上没有win8的环境，所以用windows service 2008 r2测试了下，是没有问题的。
可能需要你通过即时沟通工具联系一下我，我到你的环境上排查一下问题。

![](https://static.zixu.hk/liaozixu.com/cms/upload/20180806/130020/3ad2603138874c31ab28e01529d82885.png)

wechat : LZX767700

**Comment by Takeos** [comment]
我猜测问题应该是日期那里多了个星期，win8日期控件那里有星期显示（我是做前端的，也不太懂，只是猜测），现在没法上图，明天有时间上个图。

**Comment by liaozixu** [comment]
好的，我已经将start time 和 end time 的两个 dateTimePicker 的格式设置为了 yyyy-MM-dd，并已push，你可以再测试一下，是否正常。
